[package]
name = "rsv"
version = "1.1.0"
authors = ["jojii <jojii@gmx.net>"]
edition = "2018"
description = "The runit sv command rewritten in rust with additional features"
license = "GPL-3.0"
readme = "README.md"
homepage =""
repository="https://github.com/JojiiOfficial/rsv"

[package.metadata.arch]
arch = ["x86_64"]
provides = ["rsv"]

[dependencies]
sys-info = "0.7.0"
sysinfo = "0.15.3"
serde = "1.0.117"
serde_derive = "1.0.117"
serde_yaml = "0.8.13"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
