[package]
name = "rsv"
version = "0.1.0"
authors = ["jojii <jojii@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sv = {path="sv"}
config = {path="config"}
structopt = { version = "0.3", default-features = false }
sysinfo = "0.3.19"
