[package]
name = "rsv"
version = "1.1.0"
authors = ["jojii <jojii@gmx.net>"]
edition = "2018"
description = "The runit sv command rewritten in rust with additional features"
license = "GPL-3.0"
readme = "README.md"
homepage =""
repository="https://github.com/JojiiOfficial/rsv"

[package.metadata.arch]
arch = ["x86_64"]
provides = ["rsv"]

[dependencies]
sv = {path="sv"}
config = {path="config"}
structopt = { version = "0.3.17", default-features = false }
